### ISSUE TITLE
License

### ISSUE THREAD

**Issue by AndreaMonzini** [revereche/lineart_to_gp#1]
Hello,
very interesting project!
Could you add the License ? ( i guess it should be GPL )

I used Potrace also as command line tool for Blender ( Before Potrace was implemented in Blender ) and it is very powerful but not optimal.
Have you tried the tracing  feature of  Opentoonz or Synfig ( similar to Opentoonz ).

I am Free and open source software supporter so i pay attention on Licenses.

Thank you !

**Comment by revereche** [comment]
I'm glad you like it! Good idea, license added.

I recently learned that Synfig uses a similar method as I do in this script (medial axis skeletonization), but I wasn't aware of that at the time. I haven't looked at Synfig in years, it's interesting but the 3d aspect of Blender is crucial to my workflow.

Thank you!!

**Comment by AndreaMonzini** [comment]
Thank you !
About Synfig algorith it's ported from OpenToonz as i can read in this page:

https://www.synfig.org/2019/12/27/whats-coming-to-synfig-1-4-0-part-2/

Anyway i plan to use Blender as well :)
